### ISSUE TITLE
Deprecation notice

### ISSUE THREAD

**Issue by minhhai2209** [katalon-studio/katalon-studio-docker#4]
Hi @devillexio and @johnallen3d, 

We've released a new official Docker image for Katalon Studio at https://github.com/katalon-studio/docker-images. It is an open-source project and will be actively maintained by the team.

I will add a deprecation notice to the current Docker image at https://hub.docker.com/r/katalonstudio/katalon-studio/. Katalon team deeply appreciate your time and effort on creating a Katalon Studio Docker image to support other users. We hope to receive feedback and contributions from you in the future.

Sincerely,
Katalon Team

**Comment by johnallen3d** [comment]
Thanks for the update @minhhai2209! It looks like the new image may simplify our CI workflow a bit. 👍
